Repository AdultOfNineteen/WINEY-iOS, pull requests merged in 2024-09, with the labels that each got.

#102 Release v1.0.5 #100
  Projects/App/Sources/ T abBar/Service/TabBarService.swift
  Projects/App/Sources/ T abBar/TabBar.swift
  Projects/App/Sources/ T abBar/TabBarInfoView.swift
  Projects/App/Sources/Analysis/Reducer/AnalysisResult/WinePreferCategory.swift
  Projects/App/Sources/Analysis/Reducer/AnalysisResult/WinePreferNation.swift
  Projects/App/Sources/Analysis/Reducer/AnalysisResult/WinePreferSmell.swift
  Projects/App/Sources/Analysis/Reducer/AnalysisResult/WinePreferTaste.swift
  Projects/App/Sources/Analysis/Reducer/AnalysisResult/WinePrice.swift
  Projects/App/Sources/Analysis/Reducer/WineAnalysisResult.swift
  Projects/App/Sources/App/Coordinator/AppCoordinator.swift
  Projects/App/Sources/App/Coordinator/AppCoordinatorView.swift
  Projects/App/Sources/App/Root/AppDelegate.swift
  Projects/App/Sources/App/Services/KakaoShareMessage.swift
  Projects/App/Sources/App/Services/KakaoSharedService.swift
  Projects/App/Sources/App/Utils/AmplitudeProvider.swift
  Projects/App/Sources/Auth/Data/APIs/UserAPI.swift
  Projects/App/Sources/Auth/Reducer/SignUp/CodeSignUp.swift
  Projects/App/Sources/CreateNote/Coordinator/WritingNoteCoordinator.swift
  Projects/App/Sources/CreateNote/Data/DTO/CreateNoteRequestDTO.swift
  Projects/App/Sources/CreateNote/Model/CreateNoteManager.swift
  Projects/App/Sources/CreateNote/Reducer/SettingAlcohol.swift
  Projects/App/Sources/CreateNote/Reducer/SettingColorSmell.swift
  Projects/App/Sources/CreateNote/Reducer/SettingMemo.swift
  Projects/App/Sources/CreateNote/Reducer/SettingTaste.swift
  Projects/App/Sources/CreateNote/Reducer/SettingVintage.swift
  Projects/App/Sources/CreateNote/Reducer/SmellList.swift
  Projects/App/Sources/CreateNote/Reducer/WineConfirm.swift
  Projects/App/Sources/CreateNote/View/SettingMemoView.swift
  Projects/App/Sources/CreateNote/View/SettingTasteView.swift
  Projects/App/Sources/Main/Data/APIs/WineAPI.swift
  Projects/App/Sources/Main/Reducer/Main.swift
  Projects/App/Sources/Map/Reducer/Map.swift
  Projects/App/Sources/Map/View/MapView.swift
  Projects/App/Sources/Note/Data/APIs/NoteAPI.swift
  Projects/App/Sources/Note/Data/DTO/NoteDTO.swift
  Projects/App/Sources/Note/Data/DTO/NoteDetailDTO.swift
  Projects/App/Sources/Note/Data/DTO/PatchNoteRequestDTO.swift
  Projects/App/Sources/Note/Reducer/BottomSheet/TwoSectionBottomSheet.swift
  Projects/App/Sources/Note/Reducer/FilteredNote.swift
  Projects/App/Sources/Note/Reducer/Note.swift
  Projects/App/Sources/Note/Reducer/NoteDetail/NoteDetail.swift
  Projects/App/Sources/Note/Services/NoteService.swift
  Projects/App/Sources/Note/View/BottomSheet/TripleSectionBottomSheetView.swift
  Projects/App/Sources/Note/View/NoteDetail/NoteDetailGraphTabView.swift
  Projects/App/Sources/Note/View/NoteDetail/NoteDetailView.swift
  Projects/App/Sources/RecommendWine/Reducer/RecommendWineDetail/SpecificWineTastingNotes.swift
  Projects/App/Sources/RecommendWine/Reducer/RecommendWineDetail/WineDetail.swift
  Projects/App/Sources/RecommendWine/Reducer/WineCard.swift
  Projects/App/Sources/RecommendWine/Reducer/WineDetail.swift
  Projects/App/Sources/RecommendWine/View/WineDetail/SpecificWineTastingNotesView.swift
  Projects/App/Sources/RecommendWine/View/WineDetail/WineDetailView.swift
  Projects/App/Sources/UserDetail/Reducer/ChangeNickname.swift
  Projects/App/Sources/UserDetail/Reducer/UserSetting.swift
  Projects/App/Sources/UserDetail/Services/UserService.swift
  Projects/App/Sources/UserInfo/Reducer/UserBadge.swift
  Projects/App/Sources/UserInfo/Reducer/UserInfo.swift
  Projects/App/Sources/WineTip/Coordinator/WineTipCoordinator.swift
  Projects/App/Sources/WineTip/Reducer/TipCard.swift
  Projects/ThirdPartyLibs/Project.swift
  Tuist/ProjectDescriptionHelpers/Target+Templates.swift
Labels: v1.05

#106 [Feat] #105 Tuist 제거 / Main Refactoring
  WINEY.xcodeproj/project.pbxproj
  WINEY/Sources/ T abBar/TabBarView.swift
  WINEY/Sources/Main/Data/DTO/RecommendWineDTO.swift
  WINEY/Sources/Main/Data/DTO/Wine TipDTO.swift
  WINEY/Sources/Main/Data/DTO/WineDTO.swift
  WINEY/Sources/Main/Screens/Coordinator/Main+Navigation.swift
  WINEY/Sources/Main/Screens/Coordinator/Main.swift
  WINEY/Sources/Main/Screens/Coordinator/MainView.swift
  WINEY/Sources/Main/Screens/RecommendWines/WineCard.swift
  WINEY/Sources/Main/Screens/RecommendWines/WineCardBackground.swift
  WINEY/Sources/Main/Screens/RecommendWines/WineCardCarousel.swift
  WINEY/Sources/Main/Screens/RecommendWines/WineCardCarouselView.swift
  WINEY/Sources/Main/Screens/RecommendWines/WineCardView.swift
  WINEY/Sources/Main/Screens/RecommendWines/WineDetail/SpecificWineTastingNotes.swift
  WINEY/Sources/Main/Screens/RecommendWines/WineDetail/SpecificWineTastingNotesView.swift
  WINEY/Sources/Main/Screens/RecommendWines/WineDetail/WineDetail.swift
  WINEY/Sources/Main/Screens/RecommendWines/WineDetail/WineDetailChartBackground.swift
  WINEY/Sources/Main/Screens/RecommendWines/WineDetail/WineDetailGraph.swift
  WINEY/Sources/Main/Screens/RecommendWines/WineDetail/WineDetailInfoMiddleView.swift
  WINEY/Sources/Main/Screens/RecommendWines/WineDetail/WineDetailView.swift
  WINEY/Sources/Main/Screens/WineTips/TipCard.swift
  WINEY/Sources/Main/Screens/WineTips/TipCardDetail.swift
  WINEY/Sources/Main/Screens/WineTips/TipCardDetailView.swift
  WINEY/Sources/Main/Screens/WineTips/TipCardList.swift
  WINEY/Sources/Main/Screens/WineTips/TipCardListView.swift
  WINEY/Sources/Main/Screens/WineTips/TipCardView.swift
  WINEY/Sources/Note/Screens/Coordinator/Note+Navigation.swift
  WINEY/Sources/Note/Screens/NoteFilter/FilterDetail.swift
  WINEY/Sources/Note/Screens/NoteFilter/FilteredNotes.swift
  WINEY/Sources/RecommendWine/Screens/WineCardScroll.swift
  WINEY/Sources/RecommendWine/Screens/WineCardScrollView.swift
Labels: Refactor, 리뷰요청 : X

#108 [Feat] #107 9월 정기배포 작업 / 노트 검색, 도수 소수점 추가
  WINEY.xcodeproj/project.pbxproj
  WINEY/Sources/CreateNote/Data/DTO/CreateNoteRequestDTO.swift
  WINEY/Sources/CreateNote/Model/CreateNoteManager.swift
  WINEY/Sources/CreateNote/Screens/SettingAlcohol.swift
  WINEY/Sources/CreateNote/Screens/SettingAlcoholView.swift
  WINEY/Sources/CreateNote/Screens/SettingMemo.swift
  WINEY/Sources/CreateNote/Screens/SettingMemoView.swift
  WINEY/Sources/CreateNote/Screens/WineSearch.swift
  WINEY/Sources/CreateNote/Screens/WineSearchCard.swift
  WINEY/Sources/CreateNote/Screens/WineSearchCardView.swift
  WINEY/Sources/CreateNote/Screens/WineSearchView.swift
  WINEY/Sources/Main/Screens/RecommendWines/WineDetail/SpecificWineTastingNotesView.swift
  WINEY/Sources/Main/Screens/RecommendWines/WineDetail/WineDetailInfoMiddleView.swift
  WINEY/Sources/Main/Screens/RecommendWines/WineDetail/WineDetailView.swift
  WINEY/Sources/Note/Data/APIs/NoteAPI.swift
  WINEY/Sources/Note/Data/DTO/PatchNoteRequestDTO.swift
  WINEY/Sources/Note/Screens/Coordinator/Note+Navigation.swift
  WINEY/Sources/Note/Screens/NoteDetail/NoteDetail+SheetDestination.swift
  WINEY/Sources/Note/Screens/NoteDetail/NoteDetailView.swift
  WINEY/WineyKit/Sources/WineyKit/Picker/CustomWheelPickerView.swift
  WINEY/WineyKit/Sources/WineyKit/Text/HighLightTextView.swift
  WINEY/WineyKit/Sources/WineyKit/Utils/Font/FontType.swift
Labels: ⚙️Feature, 리뷰요청 : X
