Repository AdultOfNineteen/WINEY-iOS, pull requests merged in 2024-07, with the labels that each got.

#91 [Refactor] #90 분석하기 오류 수정
  Projects/App/Sources/Analysis/Data/DTO/TasteAnalysisDTO.swift
  Projects/App/Sources/Analysis/Reducer/AnalysisResult/WinePreferNation.swift
  Projects/App/Sources/Analysis/View/AnalysisResult/WineAnalysisCarouselView.swift
  Projects/App/Sources/Analysis/View/AnalysisResult/WineAnalysisCategoryTitle.swift
  Projects/App/Sources/Analysis/View/AnalysisResult/WineAnalysisPieChartView.swift
  Projects/App/Sources/Analysis/View/AnalysisResult/WinePreferCategoryView.swift
  Projects/App/Sources/Analysis/View/AnalysisResult/WinePreferNationView.swift
  Projects/App/Sources/Analysis/View/AnalysisResult/WinePreferSmellView.swift
  Projects/App/Sources/Analysis/View/AnalysisResult/WinePreferTasteView.swift
  Projects/App/Sources/Analysis/View/AnalysisResult/WinePriceView.swift
  Projects/App/Sources/Analysis/View/AnalysisResult/WineyPieChart.swift
  Projects/App/Sources/Analysis/View/WineAnalysisResultView.swift
Labels: Refactor, 리뷰요청 : X

#93 [Feat] #92 Amplitude 설정
  .package.resolved
  Projects/App/Sources/App/Root/AppDelegate.swift
  Projects/App/Sources/App/Utils/AmplitudeProvider.swift
Labels: 리뷰요청 : X

#95 Update V1.04
  .package.resolved
  Projects/App/Resources/Assets.xcassets/Auth/SignUp/welcome_WineGroup.imageset/Contents.json
  Projects/App/Resources/Assets.xcassets/Auth/SignUp/welcome_WineGroup.imageset/WelcomeWineGroup.png
  Projects/App/Resources/Assets.xcassets/Auth/SignUp/welcome_WineGroup.imageset/WelcomeWineGroup@2x.png
  Projects/App/Resources/Assets.xcassets/Auth/SignUp/welcome_WineGroup.imageset/WelcomeWineGroup@3x.png
  Projects/App/Sources/Analysis/Data/DTO/TasteAnalysisDTO.swift
  Projects/App/Sources/Analysis/Reducer/AnalysisResult/WinePreferNation.swift
  Projects/App/Sources/Analysis/View/AnalysisResult/WineAnalysisCarouselView.swift
  Projects/App/Sources/Analysis/View/AnalysisResult/WineAnalysisCategoryTitle.swift
  Projects/App/Sources/Analysis/View/AnalysisResult/WineAnalysisPieChartView.swift
  Projects/App/Sources/Analysis/View/AnalysisResult/WinePreferCategoryView.swift
  Projects/App/Sources/Analysis/View/AnalysisResult/WinePreferNationView.swift
  Projects/App/Sources/Analysis/View/AnalysisResult/WinePreferSmellView.swift
  Projects/App/Sources/Analysis/View/AnalysisResult/WinePreferTasteView.swift
  Projects/App/Sources/Analysis/View/AnalysisResult/WinePriceView.swift
  Projects/App/Sources/Analysis/View/AnalysisResult/WineyPieChart.swift
  Projects/App/Sources/Analysis/View/WineAnalysisResultView.swift
  Projects/App/Sources/App/Root/AppDelegate.swift
  Projects/App/Sources/App/Utils/AmplitudeProvider.swift
  Projects/App/Sources/Auth/Coordinator/AuthCoordinator.swift
  Projects/App/Sources/Auth/Reducer/SignUp/FlavorSignUp.swift
  Projects/App/Sources/Auth/Reducer/SignUp/WelcomeSignUp.swift
  Projects/App/Sources/Auth/View/SignUp/WelcomeSignUpView.swift
  Projects/App/Sources/CreateNote/Reducer/SettingMemo.swift
  Projects/App/Sources/CreateNote/View/SettingColorSmellView.swift
  Projects/App/Sources/Main/Model/WineCardData.swift
  Projects/App/Sources/Note/Data/DTO/NoteDetailDTO.swift
  Projects/App/Sources/Note/Model/NoteManager.swift
  Projects/App/Sources/Note/Reducer/FilteredNote.swift
  Projects/App/Sources/Note/Reducer/NoteDetail/NoteDetail.swift
  Projects/App/Sources/Note/View/NoteCardScrollView.swift
  Projects/App/Sources/Note/View/NoteDetail/NoteDetailGraphTabView.swift
  Projects/App/Sources/Note/View/NoteDetail/NoteDetailView.swift
  Projects/App/Sources/UserInfo/Reducer/UserInfo.swift
  Projects/App/Sources/UserInfo/View/UserInfoView.swift
  Projects/ThirdPartyLibs/Project.swift
  Tuist/Dependencies.swift
  Tuist/ProjectDescriptionHelpers/InfoPlist+Template.swift
Labels: 리뷰요청 : 🍷🍷🍷, Update Version
